[versions]
agp = "8.3.0"
androidxJunit = "1.3.0"
appcompatVersion = "1.7.1"
cardview = "1.0.0"
datastorePreferences = "1.1.1"
espressoCoreVersion = "3.7.0"
firebaseBom = "32.7.0"
firebaseFirestore = "26.0.2"
firebaseAuth = "24.0.1"
firebaseStorage = "22.0.1"
googleServices = "4.4.4"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
materialVersion = "1.13.0"
playServicesMaps = "18.2.0"
playServicesLocation = "21.0.1"
zxingAndroidEmbedded = "4.3.0"

[libraries]
appcompat-v171 = { module = "androidx.appcompat:appcompat", version.ref = "appcompatVersion" }
cardview = { module = "androidx.cardview:cardview", version.ref = "cardview" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
espresso-core-v370 = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCoreVersion" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-firestore = { module = "com.google.firebase:firebase-firestore", version.ref = "firebaseFirestore" }
firebase-auth = { module = "com.google.firebase:firebase-auth", version.ref = "firebaseAuth" }
firebase-storage = { module = "com.google.firebase:firebase-storage", version.ref = "firebaseStorage" }
google-services = { module = "com.google.gms:google-services", version.ref = "googleServices" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
junit-v130 = { module = "androidx.test.ext:junit", version.ref = "androidxJunit" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
material-v1130 = { module = "com.google.android.material:material", version.ref = "materialVersion" }
play-services-maps = { module = "com.google.android.gms:play-services-maps", version.ref = "playServicesMaps" }
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocation" }
zxing-android-embedded = { module = "com.journeyapps:zxing-android-embedded", version.ref = "zxingAndroidEmbedded" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }

